test_absolute (__main__.TestExercice) ... ok
test_factorial (__main__.TestExercice) ... FAIL
test_prefixes (__main__.TestExercice) ... ok
test_summation (__main__.TestExercice) ... ok
test_verify_ages (__main__.TestExercice) ... ok

======================================================================
FAIL: test_factorial (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 62, in test_factorial
    'Mauvaise réponse'
AssertionError: Lists differ: [3628800, 3628800, 3628800, 3628800] != [1, 6, 40320, 3628800]

First differing element 0:
3628800
1

- [3628800, 3628800, 3628800, 3628800]
+ [1, 6, 40320, 3628800] : Mauvaise réponse

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=1)
